### ISSUE TITLE
Exception when using CryptoStream: Flush not supported

### ISSUE THREAD

**Issue by aviadmini** [microknights/SplitStream#4]
Happens during FlushFinalBlock which is required in CryptoStream

**Comment by microknights** [comment]
@aviadmini Can you show me the code, or make a reproduceable example?

**Comment by aviadmini** [comment]
Likely an issue on my end. I was unable to reproduce this with a sandboxed example, and I've already moved on on the actual application. I'll re-open if I manage to get one
